/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_STRUCT_PB_H_INCLUDED
#define PB_GOOGLE_PROTOBUF_GOOGLE_PROTOBUF_STRUCT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Represents a JSON `null`.

 `NullValue` is a sentinel, using an enum with only one value to represent
 the null value for the `Value` type union.

 A field of type `NullValue` with any value other than `0` is considered
 invalid. Most ProtoJSON serializers will emit a Value with a `null_value` set
 as a JSON `null` regardless of the integer value, and so will round trip to
 a `0` value. */
typedef enum _google_protobuf_NullValue {
    /* Null value. */
    google_protobuf_NullValue_NULL_VALUE = 0
} google_protobuf_NullValue;

/* Struct definitions */
/* Represents a JSON object.

 An unordered key-value map, intending to perfectly capture the semantics of a
 JSON object. This enables parsing any arbitrary JSON payload as a message
 field in ProtoJSON format.

 This follows RFC 8259 guidelines for interoperable JSON: notably this type
 cannot represent large Int64 values or `NaN`/`Infinity` numbers,
 since the JSON format generally does not support those values in its number
 type.

 If you do not intend to parse arbitrary JSON into your message, a custom
 typed message should be preferred instead of using this type. */
typedef struct _google_protobuf_Struct {
    /* Unordered map of dynamically typed values. */
    pb_size_t fields_count;
    struct _google_protobuf_Struct_FieldsEntry *fields;
} google_protobuf_Struct;

/* Represents a JSON array. */
typedef struct _google_protobuf_ListValue {
    /* Repeated field of dynamically typed values. */
    pb_size_t values_count;
    struct _google_protobuf_Value *values;
} google_protobuf_ListValue;

/* Represents a JSON value.

 `Value` represents a dynamically typed value which can be either
 null, a number, a string, a boolean, a recursive struct value, or a
 list of values. A producer of value is expected to set one of these
 variants. Absence of any variant is an invalid state. */
typedef struct _google_protobuf_Value {
    pb_size_t which_kind;
    union {
        /* Represents a JSON `null`. */
        google_protobuf_NullValue null_value;
        /* Represents a JSON number. Must not be `NaN`, `Infinity` or
     `-Infinity`, since those are not supported in JSON. This also cannot
     represent large Int64 values, since JSON format generally does not
     support them in its number type. */
        double number_value;
        /* Represents a JSON string. */
        char *string_value;
        /* Represents a JSON boolean (`true` or `false` literal in JSON). */
        bool bool_value;
        /* Represents a JSON object. */
        google_protobuf_Struct struct_value;
        /* Represents a JSON array. */
        google_protobuf_ListValue list_value;
    } kind;
} google_protobuf_Value;

typedef struct _google_protobuf_Struct_FieldsEntry {
    char *key;
    bool has_value;
    google_protobuf_Value value;
} google_protobuf_Struct_FieldsEntry;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _google_protobuf_NullValue_MIN google_protobuf_NullValue_NULL_VALUE
#define _google_protobuf_NullValue_MAX google_protobuf_NullValue_NULL_VALUE
#define _google_protobuf_NullValue_ARRAYSIZE ((google_protobuf_NullValue)(google_protobuf_NullValue_NULL_VALUE+1))



#define google_protobuf_Value_kind_null_value_ENUMTYPE google_protobuf_NullValue



/* Initializer values for message structs */
#define google_protobuf_Struct_init_default      {0, NULL}
#define google_protobuf_Struct_FieldsEntry_init_default {NULL, false, google_protobuf_Value_init_default}
#define google_protobuf_Value_init_default       {0, {_google_protobuf_NullValue_MIN}}
#define google_protobuf_ListValue_init_default   {0, NULL}
#define google_protobuf_Struct_init_zero         {0, NULL}
#define google_protobuf_Struct_FieldsEntry_init_zero {NULL, false, google_protobuf_Value_init_zero}
#define google_protobuf_Value_init_zero          {0, {_google_protobuf_NullValue_MIN}}
#define google_protobuf_ListValue_init_zero      {0, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define google_protobuf_Struct_fields_tag        1
#define google_protobuf_ListValue_values_tag     1
#define google_protobuf_Value_null_value_tag     1
#define google_protobuf_Value_number_value_tag   2
#define google_protobuf_Value_string_value_tag   3
#define google_protobuf_Value_bool_value_tag     4
#define google_protobuf_Value_struct_value_tag   5
#define google_protobuf_Value_list_value_tag     6
#define google_protobuf_Struct_FieldsEntry_key_tag 1
#define google_protobuf_Struct_FieldsEntry_value_tag 2

/* Struct field encoding specification for nanopb */
#define google_protobuf_Struct_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  fields,            1)
#define google_protobuf_Struct_CALLBACK NULL
#define google_protobuf_Struct_DEFAULT NULL
#define google_protobuf_Struct_fields_MSGTYPE google_protobuf_Struct_FieldsEntry

#define google_protobuf_Struct_FieldsEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define google_protobuf_Struct_FieldsEntry_CALLBACK NULL
#define google_protobuf_Struct_FieldsEntry_DEFAULT NULL
#define google_protobuf_Struct_FieldsEntry_value_MSGTYPE google_protobuf_Value

#define google_protobuf_Value_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (kind,null_value,kind.null_value),   1) \
X(a, STATIC,   ONEOF,    DOUBLE,   (kind,number_value,kind.number_value),   2) \
X(a, POINTER,  ONEOF,    STRING,   (kind,string_value,kind.string_value),   3) \
X(a, STATIC,   ONEOF,    BOOL,     (kind,bool_value,kind.bool_value),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,struct_value,kind.struct_value),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,list_value,kind.list_value),   6)
#define google_protobuf_Value_CALLBACK NULL
#define google_protobuf_Value_DEFAULT NULL
#define google_protobuf_Value_kind_struct_value_MSGTYPE google_protobuf_Struct
#define google_protobuf_Value_kind_list_value_MSGTYPE google_protobuf_ListValue

#define google_protobuf_ListValue_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  values,            1)
#define google_protobuf_ListValue_CALLBACK NULL
#define google_protobuf_ListValue_DEFAULT NULL
#define google_protobuf_ListValue_values_MSGTYPE google_protobuf_Value

extern const pb_msgdesc_t google_protobuf_Struct_msg;
extern const pb_msgdesc_t google_protobuf_Struct_FieldsEntry_msg;
extern const pb_msgdesc_t google_protobuf_Value_msg;
extern const pb_msgdesc_t google_protobuf_ListValue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define google_protobuf_Struct_fields &google_protobuf_Struct_msg
#define google_protobuf_Struct_FieldsEntry_fields &google_protobuf_Struct_FieldsEntry_msg
#define google_protobuf_Value_fields &google_protobuf_Value_msg
#define google_protobuf_ListValue_fields &google_protobuf_ListValue_msg

/* Maximum encoded size of messages (where known) */
/* google_protobuf_Struct_size depends on runtime parameters */
/* google_protobuf_Struct_FieldsEntry_size depends on runtime parameters */
/* google_protobuf_Value_size depends on runtime parameters */
/* google_protobuf_ListValue_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
