// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { Value } from "./Value";

export class ListValue {
  static encode(message: ListValue, writer: Writer): void {
    const values = message.values;
    for (let i: i32 = 0; i < values.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Value.encode(values[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ListValue {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ListValue();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.values.push(Value.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  values: Array<Value>;

  constructor(values: Array<Value> = []) {
    this.values = values;
  }
}
