// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { Value } from "./Value";

export class Struct {
  static encode(message: Struct, writer: Writer): void {
    const fields = message.fields;
    if (fields !== null) {
      const fieldsKeys = fields.keys();
      for (let i: i32 = 0; i < fieldsKeys.length; ++i) {
        const fieldsKey = fieldsKeys[i];
        writer.uint32(10);
        writer.fork();
        writer.uint32(10);
        writer.string(fieldsKey);
        writer.uint32(18);
        writer.fork();
        Value.encode(fields.get(fieldsKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }
  }

  static decode(reader: Reader, length: i32): Struct {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Struct();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          let fieldsKey: string = "";
          let fieldsValue: Value | null = null;
          let fieldsHasKey: bool = false;
          let fieldsHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                fieldsKey = reader.string();
                fieldsHasKey = true;
                break;

              case 2:
                fieldsValue = Value.decode(reader, reader.uint32());
                fieldsHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.fields === null) {
              message.fields = new Map<string, Value>();
            }
            const fields = message.fields;
            if (
              fields !== null &&
              fieldsHasKey &&
              fieldsHasValue &&
              fieldsValue !== null
            ) {
              fields.set(fieldsKey, fieldsValue);
            }
          }
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  fields: Map<string, Value>;

  constructor(fields: Map<string, Value> = new Map()) {
    this.fields = fields;
  }
}
