/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_APIEXTENSIONS_FN_PROTO_V1_RUN_FUNCTION_PB_H_INCLUDED
#define PB_APIEXTENSIONS_FN_PROTO_V1_RUN_FUNCTION_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/duration.pb.h"
#include "google/protobuf/struct.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Capability indicates that Crossplane supports a particular feature.
 Functions can check for capabilities to determine whether Crossplane will
 honor a particular request or response field. */
typedef enum _fnv1_Capability {
    fnv1_Capability_CAPABILITY_UNSPECIFIED = 0,
    /* Crossplane sends capabilities in RequestMeta. If this capability is
 present, the function knows that if another capability is absent, it's
 because Crossplane doesn't support it (not because Crossplane predates
 capability advertisement). Added in Crossplane v2.2. */
    fnv1_Capability_CAPABILITY_CAPABILITIES = 1,
    /* Crossplane supports the requirements.resources field. Functions can return
 resource requirements and Crossplane will fetch the requested resources and
 return them in required_resources. Added in Crossplane v1.15. */
    fnv1_Capability_CAPABILITY_REQUIRED_RESOURCES = 2,
    /* Crossplane supports the credentials field. Functions can receive
 credentials from secrets specified in the Composition. Added in Crossplane
 v1.16. */
    fnv1_Capability_CAPABILITY_CREDENTIALS = 3,
    /* Crossplane supports the conditions field. Functions can return status
 conditions to be applied to the XR and optionally its claim. Added in
 Crossplane v1.17. */
    fnv1_Capability_CAPABILITY_CONDITIONS = 4,
    /* Crossplane supports the requirements.schemas field. Functions can request
 OpenAPI schemas and Crossplane will return them in required_schemas. Added
 in Crossplane v2.2. */
    fnv1_Capability_CAPABILITY_REQUIRED_SCHEMAS = 5
} fnv1_Capability;

/* Ready indicates whether a resource should be considered ready. */
typedef enum _fnv1_Ready {
    fnv1_Ready_READY_UNSPECIFIED = 0,
    /* True means the resource has been observed to be ready. */
    fnv1_Ready_READY_TRUE = 1,
    /* False means the resource has not been observed to be ready. */
    fnv1_Ready_READY_FALSE = 2
} fnv1_Ready;

/* Severity of function results. */
typedef enum _fnv1_Severity {
    fnv1_Severity_SEVERITY_UNSPECIFIED = 0,
    /* Fatal results are fatal; subsequent functions may run, but the function
 pipeline run will be considered a failure and the first fatal result will
 be returned as an error. */
    fnv1_Severity_SEVERITY_FATAL = 1,
    /* Warning results are non-fatal; the entire pipeline will run to completion
 but warning events and debug logs associated with the XR or Operation will
 be emitted. */
    fnv1_Severity_SEVERITY_WARNING = 2,
    /* Normal results are emitted as normal events and debug logs associated with
 the XR or operation. */
    fnv1_Severity_SEVERITY_NORMAL = 3
} fnv1_Severity;

/* Target of function results and conditions. */
typedef enum _fnv1_Target {
    /* If the target is unspecified, the result targets the XR. */
    fnv1_Target_TARGET_UNSPECIFIED = 0,
    /* Target the XR. Results that target the XR should include detailed, advanced
 information. */
    fnv1_Target_TARGET_COMPOSITE = 1,
    /* Target the XR and the claim. Results that target the XR and the claim
 should include only end-user friendly information. */
    fnv1_Target_TARGET_COMPOSITE_AND_CLAIM = 2
} fnv1_Target;

typedef enum _fnv1_Status {
    fnv1_Status_STATUS_CONDITION_UNSPECIFIED = 0,
    fnv1_Status_STATUS_CONDITION_UNKNOWN = 1,
    fnv1_Status_STATUS_CONDITION_TRUE = 2,
    fnv1_Status_STATUS_CONDITION_FALSE = 3
} fnv1_Status;

/* Struct definitions */
/* CredentialData loaded by Crossplane, for example from a Secret. */
typedef struct _fnv1_CredentialData {
    pb_size_t data_count;
    struct _fnv1_CredentialData_DataEntry *data;
} fnv1_CredentialData;

/* Credentials that a function may use to communicate with an external system. */
typedef struct _fnv1_Credentials {
    pb_size_t which_source;
    union {
        /* Credential data loaded by Crossplane, for example from a Secret. */
        fnv1_CredentialData credential_data;
    } source;
} fnv1_Credentials;

typedef struct _fnv1_RunFunctionRequest_CredentialsEntry {
    char *key;
    bool has_value;
    fnv1_Credentials value;
} fnv1_RunFunctionRequest_CredentialsEntry;

typedef struct _fnv1_CredentialData_DataEntry {
    char *key;
    pb_bytes_array_t *value;
} fnv1_CredentialData_DataEntry;

/* Resources represents the state of several Crossplane resources. */
typedef struct _fnv1_Resources {
    pb_size_t items_count;
    struct _fnv1_Resource *items;
} fnv1_Resources;

typedef struct _fnv1_RunFunctionRequest_ExtraResourcesEntry {
    char *key;
    bool has_value;
    fnv1_Resources value;
} fnv1_RunFunctionRequest_ExtraResourcesEntry;

typedef struct _fnv1_RunFunctionRequest_RequiredResourcesEntry {
    char *key;
    bool has_value;
    fnv1_Resources value;
} fnv1_RunFunctionRequest_RequiredResourcesEntry;

/* RequestMeta contains metadata pertaining to a RunFunctionRequest. */
typedef struct _fnv1_RequestMeta {
    /* An opaque string identifying a request. Requests with identical tags will
 be otherwise identical. */
    char *tag;
    /* Capabilities supported by this version of Crossplane. Functions may use
 this to determine whether Crossplane will honor certain fields in their
 response, or populate certain fields in their request. */
    pb_size_t capabilities_count;
    fnv1_Capability *capabilities;
} fnv1_RequestMeta;

/* Requirements that must be satisfied for a function to run successfully. */
typedef struct _fnv1_Requirements {
    /* Resources that this function requires. The map key uniquely identifies the
 group of resources.

 Deprecated: Use resources instead. */
    pb_size_t extra_resources_count;
    struct _fnv1_Requirements_ExtraResourcesEntry *extra_resources;
    /* Resources that this function requires. The map key uniquely identifies the
 group of resources. */
    pb_size_t resources_count;
    struct _fnv1_Requirements_ResourcesEntry *resources;
    /* Schemas that this function requires. The map key uniquely identifies the
 schema request. */
    pb_size_t schemas_count;
    struct _fnv1_Requirements_SchemasEntry *schemas;
} fnv1_Requirements;

/* SchemaSelector identifies a resource kind whose OpenAPI schema is requested. */
typedef struct _fnv1_SchemaSelector {
    /* API version of the resource kind, e.g. "example.org/v1". */
    char *api_version;
    /* Kind of resource, e.g. "MyResource". */
    char *kind;
} fnv1_SchemaSelector;

typedef struct _fnv1_Requirements_SchemasEntry {
    char *key;
    bool has_value;
    fnv1_SchemaSelector value;
} fnv1_Requirements_SchemasEntry;

/* Schema represents the OpenAPI schema for a resource kind. */
typedef struct _fnv1_Schema {
    /* The OpenAPI v3 schema of the resource kind as unstructured JSON.
 For CRDs this is the spec.versions[].schema.openAPIV3Schema field.
 Empty if Crossplane could not find a schema for the requested kind. */
    bool has_openapi_v3;
    google_protobuf_Struct openapi_v3;
} fnv1_Schema;

typedef struct _fnv1_RunFunctionRequest_RequiredSchemasEntry {
    char *key;
    bool has_value;
    fnv1_Schema value;
} fnv1_RunFunctionRequest_RequiredSchemasEntry;

/* MatchLabels defines a set of labels to match resources against. */
typedef struct _fnv1_MatchLabels {
    pb_size_t labels_count;
    struct _fnv1_MatchLabels_LabelsEntry *labels;
} fnv1_MatchLabels;

/* ResourceSelector selects a group of resources, either by name or by label. */
typedef struct _fnv1_ResourceSelector {
    /* API version of resources to select. */
    char *api_version;
    /* Kind of resources to select. */
    char *kind;
    pb_size_t which_match;
    union {
        /* Match the resource with this name. */
        char *match_name;
        /* Match all resources with these labels. */
        fnv1_MatchLabels match_labels;
    } match;
    /* Match resources in this namespace. Omit namespace to match cluster scoped
 resources, or to match namespaced resources by labels across all
 namespaces. */
    char *namespace;
} fnv1_ResourceSelector;

typedef struct _fnv1_Requirements_ExtraResourcesEntry {
    char *key;
    bool has_value;
    fnv1_ResourceSelector value;
} fnv1_Requirements_ExtraResourcesEntry;

typedef struct _fnv1_Requirements_ResourcesEntry {
    char *key;
    bool has_value;
    fnv1_ResourceSelector value;
} fnv1_Requirements_ResourcesEntry;

typedef struct _fnv1_MatchLabels_LabelsEntry {
    char *key;
    char *value;
} fnv1_MatchLabels_LabelsEntry;

/* ResponseMeta contains metadata pertaining to a RunFunctionResponse. */
typedef struct _fnv1_ResponseMeta {
    /* An opaque string identifying the content of the request. Must match the
 meta.tag of the corresponding RunFunctionRequest. */
    char *tag;
    /* Time-to-live of this response. Crossplane will call the function again when
 the TTL expires. Crossplane may cache the response to avoid calling the
 function again until the TTL expires. */
    bool has_ttl;
    google_protobuf_Duration ttl;
} fnv1_ResponseMeta;

/* A Resource represents the state of a Kubernetes resource. */
typedef struct _fnv1_Resource {
    /* The JSON representation of the resource.

 * Crossplane will set this field in a RunFunctionRequest to the entire
 observed state of a resource - including its metadata, spec, and status.

 * A function should set this field in a RunFunctionRequest to communicate
 the desired state of the resource.

 * A function may only specify the desired status of a XR - not its metadata
 or spec. A function should not return desired metadata or spec for a XR.
 This will be ignored.

 * A function may not specify the desired status of any other resource -
 e.g. composed resources. It may only specify their metadata and spec.
 Status will be ignored. */
    bool has_resource;
    google_protobuf_Struct resource;
    /* The resource's connection details.

 * Crossplane will set this field in a RunFunctionRequest to communicate the
 the observed connection details of a composite or composed resource.

 * A function should set this field in a RunFunctionResponse to indicate the
 desired connection details of legacy XRs. For modern XRs, this will be ignored.

 * A function should not set this field in a RunFunctionResponse to indicate
 the desired connection details of a composed resource. This will be
 ignored.

 Connection details are only used for composition. They're ignored by
 Operations. */
    pb_size_t connection_details_count;
    struct _fnv1_Resource_ConnectionDetailsEntry *connection_details;
    /* Ready indicates whether the resource should be considered ready.

 * Crossplane will never set this field in a RunFunctionRequest.

 * A function should set this field to READY_TRUE in a RunFunctionResponse
 to indicate that a desired resource is ready.

 * A function should set this field to READY_TRUE in a RunFunctionResponse
 to indicate that a desired XR is ready. This overwrites the standard
 readiness detection that determines the ready state of the composite by the
 ready state of the composed resources.

 Ready is only used for composition. It's ignored by Operations. */
    fnv1_Ready ready;
} fnv1_Resource;

/* State of the XR (XR) and any resources. */
typedef struct _fnv1_State {
    /* The state of the XR (XR). */
    bool has_composite;
    fnv1_Resource composite;
    /* The state of any other resources. In composition functions these are the
 composed resources. In operation functions they're arbitrary resources that
 the operation wants to create or update. */
    pb_size_t resources_count;
    struct _fnv1_State_ResourcesEntry *resources;
} fnv1_State;

/* A RunFunctionRequest requests that the function be run. */
typedef struct _fnv1_RunFunctionRequest {
    /* Metadata pertaining to this request. */
    bool has_meta;
    fnv1_RequestMeta meta;
    /* The observed state prior to invocation of a function pipeline. State passed
 to each function is fresh as of the time the pipeline was invoked, not as
 of the time each function was invoked. */
    bool has_observed;
    fnv1_State observed;
    /* Desired state according to a function pipeline. The state passed to a
 particular function may have been accumulated by previous functions in the
 pipeline.

 Note that the desired state must be a partial object with only the fields
 that this function (and its predecessors in the pipeline) wants to have set
 in the object. Copying a non-partial observed state to desired is most
 likely not what you want to do. Leaving out fields that had been returned
 as desired before will result in them being deleted from the objects in the
 cluster. */
    bool has_desired;
    fnv1_State desired;
    /* Optional input specific to this function invocation. A JSON representation
 of the 'input' block of the relevant entry in a function pipeline. */
    bool has_input;
    google_protobuf_Struct input;
    /* Optional context. Crossplane may pass arbitrary contextual information to a
 function. A function may also return context in its RunFunctionResponse,
 and that context will be passed to subsequent functions. Crossplane
 discards all context returned by the last function in the pipeline. */
    bool has_context;
    google_protobuf_Struct context;
    /* Optional resources that the function specified in its requirements. Note
 that resources is a map to Resources, plural. The map key corresponds to
 the key in a RunFunctionResponse's requirements.extra_resources field. If a
 function requested extra resources that did not exist, Crossplane sets
 the map key to an empty Resources message to indicate that it attempted to
 satisfy the request. This field is only populated when the function uses
 extra_resources in its requirements.

 Deprecated: Use required_resources instead. */
    pb_size_t extra_resources_count;
    struct _fnv1_RunFunctionRequest_ExtraResourcesEntry *extra_resources;
    /* Optional credentials that this function may use to communicate with an
 external system. */
    pb_size_t credentials_count;
    struct _fnv1_RunFunctionRequest_CredentialsEntry *credentials;
    /* Optional resources that the function specified in its requirements. Note
 that resources is a map to Resources, plural. The map key corresponds to
 the key in a RunFunctionResponse's requirements.resources field. If a
 function requested required resources that did not exist, Crossplane sets
 the map key to an empty Resources message to indicate that it attempted to
 satisfy the request. This field is only populated when the function uses
 resources in its requirements. */
    pb_size_t required_resources_count;
    struct _fnv1_RunFunctionRequest_RequiredResourcesEntry *required_resources;
    /* Optional schemas that the function specified in its requirements. The map
 key corresponds to the key in a RunFunctionResponse's requirements.schemas
 field. If a function requested a schema that could not be found, Crossplane
 sets the map key to an empty Schema message to indicate that it attempted
 to satisfy the request. */
    pb_size_t required_schemas_count;
    struct _fnv1_RunFunctionRequest_RequiredSchemasEntry *required_schemas;
} fnv1_RunFunctionRequest;

/* A RunFunctionResponse contains the result of a function run. */
typedef struct _fnv1_RunFunctionResponse {
    /* Metadata pertaining to this response. */
    bool has_meta;
    fnv1_ResponseMeta meta;
    /* Desired state according to a function pipeline. functions may add desired
 state, and may mutate or delete any part of the desired state they are
 concerned with. A function must pass through any part of the desired state
 that it is not concerned with.

 Note that the desired state must be a partial object with only the fields
 that this function (and its predecessors in the pipeline) wants to have set
 in the object. Copying a non-partial observed state to desired is most
 likely not what you want to do. Leaving out fields that had been returned
 as desired before will result in them being deleted from the objects in the
 cluster. */
    bool has_desired;
    fnv1_State desired;
    /* Results of the function run. Results are used for observability purposes. */
    pb_size_t results_count;
    struct _fnv1_Result *results;
    /* Optional context to be passed to the next function in the pipeline as part
 of the RunFunctionRequest. Dropped on the last function in the pipeline. */
    bool has_context;
    google_protobuf_Struct context;
    /* Requirements that must be satisfied for this function to run successfully. */
    bool has_requirements;
    fnv1_Requirements requirements;
    /* Status conditions to be applied to the XR. Conditions may also optionally
 be applied to the XR's associated claim.

 Conditions are only used for composition. They're ignored by Operations. */
    pb_size_t conditions_count;
    struct _fnv1_Condition *conditions;
    /* Optional output specific to this function invocation.

 Only Operations use function output. XRs will discard any function output. */
    bool has_output;
    google_protobuf_Struct output;
} fnv1_RunFunctionResponse;

typedef struct _fnv1_State_ResourcesEntry {
    char *key;
    bool has_value;
    fnv1_Resource value;
} fnv1_State_ResourcesEntry;

typedef struct _fnv1_Resource_ConnectionDetailsEntry {
    char *key;
    pb_bytes_array_t *value;
} fnv1_Resource_ConnectionDetailsEntry;

/* A Result of running a function. */
typedef struct _fnv1_Result {
    /* Severity of this result. */
    fnv1_Severity severity;
    /* Human-readable details about the result. */
    char *message;
    /* Optional PascalCase, machine-readable reason for this result. If omitted,
 the value will be ComposeResources. */
    char *reason;
    /* The resources this result targets. */
    bool has_target;
    fnv1_Target target;
} fnv1_Result;

/* Status condition to be applied to the XR. Condition may also optionally be
 applied to the XR's associated claim. For detailed information on proper
 usage of status conditions, please see
 https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties. */
typedef struct _fnv1_Condition {
    /* Type of condition in PascalCase. */
    char *type;
    /* Status of the condition. */
    fnv1_Status status;
    /* Reason contains a programmatic identifier indicating the reason for the
 condition's last transition. Producers of specific condition types may
 define expected values and meanings for this field, and whether the values
 are considered a guaranteed API. The value should be a PascalCase string.
 This field may not be empty. */
    char *reason;
    /* Message is a human readable message indicating details about the
 transition. This may be an empty string. */
    char *message;
    /* The resources this condition targets. */
    bool has_target;
    fnv1_Target target;
} fnv1_Condition;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _fnv1_Capability_MIN fnv1_Capability_CAPABILITY_UNSPECIFIED
#define _fnv1_Capability_MAX fnv1_Capability_CAPABILITY_REQUIRED_SCHEMAS
#define _fnv1_Capability_ARRAYSIZE ((fnv1_Capability)(fnv1_Capability_CAPABILITY_REQUIRED_SCHEMAS+1))

#define _fnv1_Ready_MIN fnv1_Ready_READY_UNSPECIFIED
#define _fnv1_Ready_MAX fnv1_Ready_READY_FALSE
#define _fnv1_Ready_ARRAYSIZE ((fnv1_Ready)(fnv1_Ready_READY_FALSE+1))

#define _fnv1_Severity_MIN fnv1_Severity_SEVERITY_UNSPECIFIED
#define _fnv1_Severity_MAX fnv1_Severity_SEVERITY_NORMAL
#define _fnv1_Severity_ARRAYSIZE ((fnv1_Severity)(fnv1_Severity_SEVERITY_NORMAL+1))

#define _fnv1_Target_MIN fnv1_Target_TARGET_UNSPECIFIED
#define _fnv1_Target_MAX fnv1_Target_TARGET_COMPOSITE_AND_CLAIM
#define _fnv1_Target_ARRAYSIZE ((fnv1_Target)(fnv1_Target_TARGET_COMPOSITE_AND_CLAIM+1))

#define _fnv1_Status_MIN fnv1_Status_STATUS_CONDITION_UNSPECIFIED
#define _fnv1_Status_MAX fnv1_Status_STATUS_CONDITION_FALSE
#define _fnv1_Status_ARRAYSIZE ((fnv1_Status)(fnv1_Status_STATUS_CONDITION_FALSE+1))











#define fnv1_RequestMeta_capabilities_ENUMTYPE fnv1_Capability













#define fnv1_Resource_ready_ENUMTYPE fnv1_Ready


#define fnv1_Result_severity_ENUMTYPE fnv1_Severity
#define fnv1_Result_target_ENUMTYPE fnv1_Target

#define fnv1_Condition_status_ENUMTYPE fnv1_Status
#define fnv1_Condition_target_ENUMTYPE fnv1_Target


/* Initializer values for message structs */
#define fnv1_RunFunctionRequest_init_default     {false, fnv1_RequestMeta_init_default, false, fnv1_State_init_default, false, fnv1_State_init_default, false, google_protobuf_Struct_init_default, false, google_protobuf_Struct_init_default, 0, NULL, 0, NULL, 0, NULL, 0, NULL}
#define fnv1_RunFunctionRequest_ExtraResourcesEntry_init_default {NULL, false, fnv1_Resources_init_default}
#define fnv1_RunFunctionRequest_CredentialsEntry_init_default {NULL, false, fnv1_Credentials_init_default}
#define fnv1_RunFunctionRequest_RequiredResourcesEntry_init_default {NULL, false, fnv1_Resources_init_default}
#define fnv1_RunFunctionRequest_RequiredSchemasEntry_init_default {NULL, false, fnv1_Schema_init_default}
#define fnv1_Credentials_init_default            {0, {fnv1_CredentialData_init_default}}
#define fnv1_CredentialData_init_default         {0, NULL}
#define fnv1_CredentialData_DataEntry_init_default {NULL, NULL}
#define fnv1_Resources_init_default              {0, NULL}
#define fnv1_RunFunctionResponse_init_default    {false, fnv1_ResponseMeta_init_default, false, fnv1_State_init_default, 0, NULL, false, google_protobuf_Struct_init_default, false, fnv1_Requirements_init_default, 0, NULL, false, google_protobuf_Struct_init_default}
#define fnv1_RequestMeta_init_default            {NULL, 0, NULL}
#define fnv1_Requirements_init_default           {0, NULL, 0, NULL, 0, NULL}
#define fnv1_Requirements_ExtraResourcesEntry_init_default {NULL, false, fnv1_ResourceSelector_init_default}
#define fnv1_Requirements_ResourcesEntry_init_default {NULL, false, fnv1_ResourceSelector_init_default}
#define fnv1_Requirements_SchemasEntry_init_default {NULL, false, fnv1_SchemaSelector_init_default}
#define fnv1_SchemaSelector_init_default         {NULL, NULL}
#define fnv1_Schema_init_default                 {false, google_protobuf_Struct_init_default}
#define fnv1_ResourceSelector_init_default       {NULL, NULL, 0, {NULL}, NULL}
#define fnv1_MatchLabels_init_default            {0, NULL}
#define fnv1_MatchLabels_LabelsEntry_init_default {NULL, NULL}
#define fnv1_ResponseMeta_init_default           {NULL, false, google_protobuf_Duration_init_default}
#define fnv1_State_init_default                  {false, fnv1_Resource_init_default, 0, NULL}
#define fnv1_State_ResourcesEntry_init_default   {NULL, false, fnv1_Resource_init_default}
#define fnv1_Resource_init_default               {false, google_protobuf_Struct_init_default, 0, NULL, _fnv1_Ready_MIN}
#define fnv1_Resource_ConnectionDetailsEntry_init_default {NULL, NULL}
#define fnv1_Result_init_default                 {_fnv1_Severity_MIN, NULL, NULL, false, _fnv1_Target_MIN}
#define fnv1_Condition_init_default              {NULL, _fnv1_Status_MIN, NULL, NULL, false, _fnv1_Target_MIN}
#define fnv1_RunFunctionRequest_init_zero        {false, fnv1_RequestMeta_init_zero, false, fnv1_State_init_zero, false, fnv1_State_init_zero, false, google_protobuf_Struct_init_zero, false, google_protobuf_Struct_init_zero, 0, NULL, 0, NULL, 0, NULL, 0, NULL}
#define fnv1_RunFunctionRequest_ExtraResourcesEntry_init_zero {NULL, false, fnv1_Resources_init_zero}
#define fnv1_RunFunctionRequest_CredentialsEntry_init_zero {NULL, false, fnv1_Credentials_init_zero}
#define fnv1_RunFunctionRequest_RequiredResourcesEntry_init_zero {NULL, false, fnv1_Resources_init_zero}
#define fnv1_RunFunctionRequest_RequiredSchemasEntry_init_zero {NULL, false, fnv1_Schema_init_zero}
#define fnv1_Credentials_init_zero               {0, {fnv1_CredentialData_init_zero}}
#define fnv1_CredentialData_init_zero            {0, NULL}
#define fnv1_CredentialData_DataEntry_init_zero  {NULL, NULL}
#define fnv1_Resources_init_zero                 {0, NULL}
#define fnv1_RunFunctionResponse_init_zero       {false, fnv1_ResponseMeta_init_zero, false, fnv1_State_init_zero, 0, NULL, false, google_protobuf_Struct_init_zero, false, fnv1_Requirements_init_zero, 0, NULL, false, google_protobuf_Struct_init_zero}
#define fnv1_RequestMeta_init_zero               {NULL, 0, NULL}
#define fnv1_Requirements_init_zero              {0, NULL, 0, NULL, 0, NULL}
#define fnv1_Requirements_ExtraResourcesEntry_init_zero {NULL, false, fnv1_ResourceSelector_init_zero}
#define fnv1_Requirements_ResourcesEntry_init_zero {NULL, false, fnv1_ResourceSelector_init_zero}
#define fnv1_Requirements_SchemasEntry_init_zero {NULL, false, fnv1_SchemaSelector_init_zero}
#define fnv1_SchemaSelector_init_zero            {NULL, NULL}
#define fnv1_Schema_init_zero                    {false, google_protobuf_Struct_init_zero}
#define fnv1_ResourceSelector_init_zero          {NULL, NULL, 0, {NULL}, NULL}
#define fnv1_MatchLabels_init_zero               {0, NULL}
#define fnv1_MatchLabels_LabelsEntry_init_zero   {NULL, NULL}
#define fnv1_ResponseMeta_init_zero              {NULL, false, google_protobuf_Duration_init_zero}
#define fnv1_State_init_zero                     {false, fnv1_Resource_init_zero, 0, NULL}
#define fnv1_State_ResourcesEntry_init_zero      {NULL, false, fnv1_Resource_init_zero}
#define fnv1_Resource_init_zero                  {false, google_protobuf_Struct_init_zero, 0, NULL, _fnv1_Ready_MIN}
#define fnv1_Resource_ConnectionDetailsEntry_init_zero {NULL, NULL}
#define fnv1_Result_init_zero                    {_fnv1_Severity_MIN, NULL, NULL, false, _fnv1_Target_MIN}
#define fnv1_Condition_init_zero                 {NULL, _fnv1_Status_MIN, NULL, NULL, false, _fnv1_Target_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define fnv1_CredentialData_data_tag             1
#define fnv1_Credentials_credential_data_tag     1
#define fnv1_RunFunctionRequest_CredentialsEntry_key_tag 1
#define fnv1_RunFunctionRequest_CredentialsEntry_value_tag 2
#define fnv1_CredentialData_DataEntry_key_tag    1
#define fnv1_CredentialData_DataEntry_value_tag  2
#define fnv1_Resources_items_tag                 1
#define fnv1_RunFunctionRequest_ExtraResourcesEntry_key_tag 1
#define fnv1_RunFunctionRequest_ExtraResourcesEntry_value_tag 2
#define fnv1_RunFunctionRequest_RequiredResourcesEntry_key_tag 1
#define fnv1_RunFunctionRequest_RequiredResourcesEntry_value_tag 2
#define fnv1_RequestMeta_tag_tag                 1
#define fnv1_RequestMeta_capabilities_tag        2
#define fnv1_Requirements_extra_resources_tag    1
#define fnv1_Requirements_resources_tag          2
#define fnv1_Requirements_schemas_tag            3
#define fnv1_SchemaSelector_api_version_tag      1
#define fnv1_SchemaSelector_kind_tag             2
#define fnv1_Requirements_SchemasEntry_key_tag   1
#define fnv1_Requirements_SchemasEntry_value_tag 2
#define fnv1_Schema_openapi_v3_tag               1
#define fnv1_RunFunctionRequest_RequiredSchemasEntry_key_tag 1
#define fnv1_RunFunctionRequest_RequiredSchemasEntry_value_tag 2
#define fnv1_MatchLabels_labels_tag              1
#define fnv1_ResourceSelector_api_version_tag    1
#define fnv1_ResourceSelector_kind_tag           2
#define fnv1_ResourceSelector_match_name_tag     3
#define fnv1_ResourceSelector_match_labels_tag   4
#define fnv1_ResourceSelector_namespace_tag      5
#define fnv1_Requirements_ExtraResourcesEntry_key_tag 1
#define fnv1_Requirements_ExtraResourcesEntry_value_tag 2
#define fnv1_Requirements_ResourcesEntry_key_tag 1
#define fnv1_Requirements_ResourcesEntry_value_tag 2
#define fnv1_MatchLabels_LabelsEntry_key_tag     1
#define fnv1_MatchLabels_LabelsEntry_value_tag   2
#define fnv1_ResponseMeta_tag_tag                1
#define fnv1_ResponseMeta_ttl_tag                2
#define fnv1_Resource_resource_tag               1
#define fnv1_Resource_connection_details_tag     2
#define fnv1_Resource_ready_tag                  3
#define fnv1_State_composite_tag                 1
#define fnv1_State_resources_tag                 2
#define fnv1_RunFunctionRequest_meta_tag         1
#define fnv1_RunFunctionRequest_observed_tag     2
#define fnv1_RunFunctionRequest_desired_tag      3
#define fnv1_RunFunctionRequest_input_tag        4
#define fnv1_RunFunctionRequest_context_tag      5
#define fnv1_RunFunctionRequest_extra_resources_tag 6
#define fnv1_RunFunctionRequest_credentials_tag  7
#define fnv1_RunFunctionRequest_required_resources_tag 8
#define fnv1_RunFunctionRequest_required_schemas_tag 9
#define fnv1_RunFunctionResponse_meta_tag        1
#define fnv1_RunFunctionResponse_desired_tag     2
#define fnv1_RunFunctionResponse_results_tag     3
#define fnv1_RunFunctionResponse_context_tag     4
#define fnv1_RunFunctionResponse_requirements_tag 5
#define fnv1_RunFunctionResponse_conditions_tag  6
#define fnv1_RunFunctionResponse_output_tag      7
#define fnv1_State_ResourcesEntry_key_tag        1
#define fnv1_State_ResourcesEntry_value_tag      2
#define fnv1_Resource_ConnectionDetailsEntry_key_tag 1
#define fnv1_Resource_ConnectionDetailsEntry_value_tag 2
#define fnv1_Result_severity_tag                 1
#define fnv1_Result_message_tag                  2
#define fnv1_Result_reason_tag                   3
#define fnv1_Result_target_tag                   4
#define fnv1_Condition_type_tag                  1
#define fnv1_Condition_status_tag                2
#define fnv1_Condition_reason_tag                3
#define fnv1_Condition_message_tag               4
#define fnv1_Condition_target_tag                5

/* Struct field encoding specification for nanopb */
#define fnv1_RunFunctionRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  observed,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  desired,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  input,             4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  context,           5) \
X(a, POINTER,  REPEATED, MESSAGE,  extra_resources,   6) \
X(a, POINTER,  REPEATED, MESSAGE,  credentials,       7) \
X(a, POINTER,  REPEATED, MESSAGE,  required_resources,   8) \
X(a, POINTER,  REPEATED, MESSAGE,  required_schemas,   9)
#define fnv1_RunFunctionRequest_CALLBACK NULL
#define fnv1_RunFunctionRequest_DEFAULT NULL
#define fnv1_RunFunctionRequest_meta_MSGTYPE fnv1_RequestMeta
#define fnv1_RunFunctionRequest_observed_MSGTYPE fnv1_State
#define fnv1_RunFunctionRequest_desired_MSGTYPE fnv1_State
#define fnv1_RunFunctionRequest_input_MSGTYPE google_protobuf_Struct
#define fnv1_RunFunctionRequest_context_MSGTYPE google_protobuf_Struct
#define fnv1_RunFunctionRequest_extra_resources_MSGTYPE fnv1_RunFunctionRequest_ExtraResourcesEntry
#define fnv1_RunFunctionRequest_credentials_MSGTYPE fnv1_RunFunctionRequest_CredentialsEntry
#define fnv1_RunFunctionRequest_required_resources_MSGTYPE fnv1_RunFunctionRequest_RequiredResourcesEntry
#define fnv1_RunFunctionRequest_required_schemas_MSGTYPE fnv1_RunFunctionRequest_RequiredSchemasEntry

#define fnv1_RunFunctionRequest_ExtraResourcesEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define fnv1_RunFunctionRequest_ExtraResourcesEntry_CALLBACK NULL
#define fnv1_RunFunctionRequest_ExtraResourcesEntry_DEFAULT NULL
#define fnv1_RunFunctionRequest_ExtraResourcesEntry_value_MSGTYPE fnv1_Resources

#define fnv1_RunFunctionRequest_CredentialsEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define fnv1_RunFunctionRequest_CredentialsEntry_CALLBACK NULL
#define fnv1_RunFunctionRequest_CredentialsEntry_DEFAULT NULL
#define fnv1_RunFunctionRequest_CredentialsEntry_value_MSGTYPE fnv1_Credentials

#define fnv1_RunFunctionRequest_RequiredResourcesEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define fnv1_RunFunctionRequest_RequiredResourcesEntry_CALLBACK NULL
#define fnv1_RunFunctionRequest_RequiredResourcesEntry_DEFAULT NULL
#define fnv1_RunFunctionRequest_RequiredResourcesEntry_value_MSGTYPE fnv1_Resources

#define fnv1_RunFunctionRequest_RequiredSchemasEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define fnv1_RunFunctionRequest_RequiredSchemasEntry_CALLBACK NULL
#define fnv1_RunFunctionRequest_RequiredSchemasEntry_DEFAULT NULL
#define fnv1_RunFunctionRequest_RequiredSchemasEntry_value_MSGTYPE fnv1_Schema

#define fnv1_Credentials_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (source,credential_data,source.credential_data),   1)
#define fnv1_Credentials_CALLBACK NULL
#define fnv1_Credentials_DEFAULT NULL
#define fnv1_Credentials_source_credential_data_MSGTYPE fnv1_CredentialData

#define fnv1_CredentialData_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  data,              1)
#define fnv1_CredentialData_CALLBACK NULL
#define fnv1_CredentialData_DEFAULT NULL
#define fnv1_CredentialData_data_MSGTYPE fnv1_CredentialData_DataEntry

#define fnv1_CredentialData_DataEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, POINTER,  SINGULAR, BYTES,    value,             2)
#define fnv1_CredentialData_DataEntry_CALLBACK NULL
#define fnv1_CredentialData_DataEntry_DEFAULT NULL

#define fnv1_Resources_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  items,             1)
#define fnv1_Resources_CALLBACK NULL
#define fnv1_Resources_DEFAULT NULL
#define fnv1_Resources_items_MSGTYPE fnv1_Resource

#define fnv1_RunFunctionResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  desired,           2) \
X(a, POINTER,  REPEATED, MESSAGE,  results,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  context,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  requirements,      5) \
X(a, POINTER,  REPEATED, MESSAGE,  conditions,        6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  output,            7)
#define fnv1_RunFunctionResponse_CALLBACK NULL
#define fnv1_RunFunctionResponse_DEFAULT NULL
#define fnv1_RunFunctionResponse_meta_MSGTYPE fnv1_ResponseMeta
#define fnv1_RunFunctionResponse_desired_MSGTYPE fnv1_State
#define fnv1_RunFunctionResponse_results_MSGTYPE fnv1_Result
#define fnv1_RunFunctionResponse_context_MSGTYPE google_protobuf_Struct
#define fnv1_RunFunctionResponse_requirements_MSGTYPE fnv1_Requirements
#define fnv1_RunFunctionResponse_conditions_MSGTYPE fnv1_Condition
#define fnv1_RunFunctionResponse_output_MSGTYPE google_protobuf_Struct

#define fnv1_RequestMeta_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   tag,               1) \
X(a, POINTER,  REPEATED, UENUM,    capabilities,      2)
#define fnv1_RequestMeta_CALLBACK NULL
#define fnv1_RequestMeta_DEFAULT NULL

#define fnv1_Requirements_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  extra_resources,   1) \
X(a, POINTER,  REPEATED, MESSAGE,  resources,         2) \
X(a, POINTER,  REPEATED, MESSAGE,  schemas,           3)
#define fnv1_Requirements_CALLBACK NULL
#define fnv1_Requirements_DEFAULT NULL
#define fnv1_Requirements_extra_resources_MSGTYPE fnv1_Requirements_ExtraResourcesEntry
#define fnv1_Requirements_resources_MSGTYPE fnv1_Requirements_ResourcesEntry
#define fnv1_Requirements_schemas_MSGTYPE fnv1_Requirements_SchemasEntry

#define fnv1_Requirements_ExtraResourcesEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define fnv1_Requirements_ExtraResourcesEntry_CALLBACK NULL
#define fnv1_Requirements_ExtraResourcesEntry_DEFAULT NULL
#define fnv1_Requirements_ExtraResourcesEntry_value_MSGTYPE fnv1_ResourceSelector

#define fnv1_Requirements_ResourcesEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define fnv1_Requirements_ResourcesEntry_CALLBACK NULL
#define fnv1_Requirements_ResourcesEntry_DEFAULT NULL
#define fnv1_Requirements_ResourcesEntry_value_MSGTYPE fnv1_ResourceSelector

#define fnv1_Requirements_SchemasEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define fnv1_Requirements_SchemasEntry_CALLBACK NULL
#define fnv1_Requirements_SchemasEntry_DEFAULT NULL
#define fnv1_Requirements_SchemasEntry_value_MSGTYPE fnv1_SchemaSelector

#define fnv1_SchemaSelector_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   api_version,       1) \
X(a, POINTER,  SINGULAR, STRING,   kind,              2)
#define fnv1_SchemaSelector_CALLBACK NULL
#define fnv1_SchemaSelector_DEFAULT NULL

#define fnv1_Schema_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  openapi_v3,        1)
#define fnv1_Schema_CALLBACK NULL
#define fnv1_Schema_DEFAULT NULL
#define fnv1_Schema_openapi_v3_MSGTYPE google_protobuf_Struct

#define fnv1_ResourceSelector_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   api_version,       1) \
X(a, POINTER,  SINGULAR, STRING,   kind,              2) \
X(a, POINTER,  ONEOF,    STRING,   (match,match_name,match.match_name),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (match,match_labels,match.match_labels),   4) \
X(a, POINTER,  OPTIONAL, STRING,   namespace,         5)
#define fnv1_ResourceSelector_CALLBACK NULL
#define fnv1_ResourceSelector_DEFAULT NULL
#define fnv1_ResourceSelector_match_match_labels_MSGTYPE fnv1_MatchLabels

#define fnv1_MatchLabels_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  labels,            1)
#define fnv1_MatchLabels_CALLBACK NULL
#define fnv1_MatchLabels_DEFAULT NULL
#define fnv1_MatchLabels_labels_MSGTYPE fnv1_MatchLabels_LabelsEntry

#define fnv1_MatchLabels_LabelsEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, POINTER,  SINGULAR, STRING,   value,             2)
#define fnv1_MatchLabels_LabelsEntry_CALLBACK NULL
#define fnv1_MatchLabels_LabelsEntry_DEFAULT NULL

#define fnv1_ResponseMeta_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   tag,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ttl,               2)
#define fnv1_ResponseMeta_CALLBACK NULL
#define fnv1_ResponseMeta_DEFAULT NULL
#define fnv1_ResponseMeta_ttl_MSGTYPE google_protobuf_Duration

#define fnv1_State_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  composite,         1) \
X(a, POINTER,  REPEATED, MESSAGE,  resources,         2)
#define fnv1_State_CALLBACK NULL
#define fnv1_State_DEFAULT NULL
#define fnv1_State_composite_MSGTYPE fnv1_Resource
#define fnv1_State_resources_MSGTYPE fnv1_State_ResourcesEntry

#define fnv1_State_ResourcesEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define fnv1_State_ResourcesEntry_CALLBACK NULL
#define fnv1_State_ResourcesEntry_DEFAULT NULL
#define fnv1_State_ResourcesEntry_value_MSGTYPE fnv1_Resource

#define fnv1_Resource_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  resource,          1) \
X(a, POINTER,  REPEATED, MESSAGE,  connection_details,   2) \
X(a, STATIC,   SINGULAR, UENUM,    ready,             3)
#define fnv1_Resource_CALLBACK NULL
#define fnv1_Resource_DEFAULT NULL
#define fnv1_Resource_resource_MSGTYPE google_protobuf_Struct
#define fnv1_Resource_connection_details_MSGTYPE fnv1_Resource_ConnectionDetailsEntry

#define fnv1_Resource_ConnectionDetailsEntry_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   key,               1) \
X(a, POINTER,  SINGULAR, BYTES,    value,             2)
#define fnv1_Resource_ConnectionDetailsEntry_CALLBACK NULL
#define fnv1_Resource_ConnectionDetailsEntry_DEFAULT NULL

#define fnv1_Result_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    severity,          1) \
X(a, POINTER,  SINGULAR, STRING,   message,           2) \
X(a, POINTER,  OPTIONAL, STRING,   reason,            3) \
X(a, STATIC,   OPTIONAL, UENUM,    target,            4)
#define fnv1_Result_CALLBACK NULL
#define fnv1_Result_DEFAULT NULL

#define fnv1_Condition_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   type,              1) \
X(a, STATIC,   SINGULAR, UENUM,    status,            2) \
X(a, POINTER,  SINGULAR, STRING,   reason,            3) \
X(a, POINTER,  OPTIONAL, STRING,   message,           4) \
X(a, STATIC,   OPTIONAL, UENUM,    target,            5)
#define fnv1_Condition_CALLBACK NULL
#define fnv1_Condition_DEFAULT NULL

extern const pb_msgdesc_t fnv1_RunFunctionRequest_msg;
extern const pb_msgdesc_t fnv1_RunFunctionRequest_ExtraResourcesEntry_msg;
extern const pb_msgdesc_t fnv1_RunFunctionRequest_CredentialsEntry_msg;
extern const pb_msgdesc_t fnv1_RunFunctionRequest_RequiredResourcesEntry_msg;
extern const pb_msgdesc_t fnv1_RunFunctionRequest_RequiredSchemasEntry_msg;
extern const pb_msgdesc_t fnv1_Credentials_msg;
extern const pb_msgdesc_t fnv1_CredentialData_msg;
extern const pb_msgdesc_t fnv1_CredentialData_DataEntry_msg;
extern const pb_msgdesc_t fnv1_Resources_msg;
extern const pb_msgdesc_t fnv1_RunFunctionResponse_msg;
extern const pb_msgdesc_t fnv1_RequestMeta_msg;
extern const pb_msgdesc_t fnv1_Requirements_msg;
extern const pb_msgdesc_t fnv1_Requirements_ExtraResourcesEntry_msg;
extern const pb_msgdesc_t fnv1_Requirements_ResourcesEntry_msg;
extern const pb_msgdesc_t fnv1_Requirements_SchemasEntry_msg;
extern const pb_msgdesc_t fnv1_SchemaSelector_msg;
extern const pb_msgdesc_t fnv1_Schema_msg;
extern const pb_msgdesc_t fnv1_ResourceSelector_msg;
extern const pb_msgdesc_t fnv1_MatchLabels_msg;
extern const pb_msgdesc_t fnv1_MatchLabels_LabelsEntry_msg;
extern const pb_msgdesc_t fnv1_ResponseMeta_msg;
extern const pb_msgdesc_t fnv1_State_msg;
extern const pb_msgdesc_t fnv1_State_ResourcesEntry_msg;
extern const pb_msgdesc_t fnv1_Resource_msg;
extern const pb_msgdesc_t fnv1_Resource_ConnectionDetailsEntry_msg;
extern const pb_msgdesc_t fnv1_Result_msg;
extern const pb_msgdesc_t fnv1_Condition_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define fnv1_RunFunctionRequest_fields &fnv1_RunFunctionRequest_msg
#define fnv1_RunFunctionRequest_ExtraResourcesEntry_fields &fnv1_RunFunctionRequest_ExtraResourcesEntry_msg
#define fnv1_RunFunctionRequest_CredentialsEntry_fields &fnv1_RunFunctionRequest_CredentialsEntry_msg
#define fnv1_RunFunctionRequest_RequiredResourcesEntry_fields &fnv1_RunFunctionRequest_RequiredResourcesEntry_msg
#define fnv1_RunFunctionRequest_RequiredSchemasEntry_fields &fnv1_RunFunctionRequest_RequiredSchemasEntry_msg
#define fnv1_Credentials_fields &fnv1_Credentials_msg
#define fnv1_CredentialData_fields &fnv1_CredentialData_msg
#define fnv1_CredentialData_DataEntry_fields &fnv1_CredentialData_DataEntry_msg
#define fnv1_Resources_fields &fnv1_Resources_msg
#define fnv1_RunFunctionResponse_fields &fnv1_RunFunctionResponse_msg
#define fnv1_RequestMeta_fields &fnv1_RequestMeta_msg
#define fnv1_Requirements_fields &fnv1_Requirements_msg
#define fnv1_Requirements_ExtraResourcesEntry_fields &fnv1_Requirements_ExtraResourcesEntry_msg
#define fnv1_Requirements_ResourcesEntry_fields &fnv1_Requirements_ResourcesEntry_msg
#define fnv1_Requirements_SchemasEntry_fields &fnv1_Requirements_SchemasEntry_msg
#define fnv1_SchemaSelector_fields &fnv1_SchemaSelector_msg
#define fnv1_Schema_fields &fnv1_Schema_msg
#define fnv1_ResourceSelector_fields &fnv1_ResourceSelector_msg
#define fnv1_MatchLabels_fields &fnv1_MatchLabels_msg
#define fnv1_MatchLabels_LabelsEntry_fields &fnv1_MatchLabels_LabelsEntry_msg
#define fnv1_ResponseMeta_fields &fnv1_ResponseMeta_msg
#define fnv1_State_fields &fnv1_State_msg
#define fnv1_State_ResourcesEntry_fields &fnv1_State_ResourcesEntry_msg
#define fnv1_Resource_fields &fnv1_Resource_msg
#define fnv1_Resource_ConnectionDetailsEntry_fields &fnv1_Resource_ConnectionDetailsEntry_msg
#define fnv1_Result_fields &fnv1_Result_msg
#define fnv1_Condition_fields &fnv1_Condition_msg

/* Maximum encoded size of messages (where known) */
/* fnv1_RunFunctionRequest_size depends on runtime parameters */
/* fnv1_RunFunctionRequest_ExtraResourcesEntry_size depends on runtime parameters */
/* fnv1_RunFunctionRequest_CredentialsEntry_size depends on runtime parameters */
/* fnv1_RunFunctionRequest_RequiredResourcesEntry_size depends on runtime parameters */
/* fnv1_RunFunctionRequest_RequiredSchemasEntry_size depends on runtime parameters */
/* fnv1_Credentials_size depends on runtime parameters */
/* fnv1_CredentialData_size depends on runtime parameters */
/* fnv1_CredentialData_DataEntry_size depends on runtime parameters */
/* fnv1_Resources_size depends on runtime parameters */
/* fnv1_RunFunctionResponse_size depends on runtime parameters */
/* fnv1_RequestMeta_size depends on runtime parameters */
/* fnv1_Requirements_size depends on runtime parameters */
/* fnv1_Requirements_ExtraResourcesEntry_size depends on runtime parameters */
/* fnv1_Requirements_ResourcesEntry_size depends on runtime parameters */
/* fnv1_Requirements_SchemasEntry_size depends on runtime parameters */
/* fnv1_SchemaSelector_size depends on runtime parameters */
/* fnv1_ResourceSelector_size depends on runtime parameters */
/* fnv1_MatchLabels_size depends on runtime parameters */
/* fnv1_MatchLabels_LabelsEntry_size depends on runtime parameters */
/* fnv1_ResponseMeta_size depends on runtime parameters */
/* fnv1_State_size depends on runtime parameters */
/* fnv1_State_ResourcesEntry_size depends on runtime parameters */
/* fnv1_Resource_size depends on runtime parameters */
/* fnv1_Resource_ConnectionDetailsEntry_size depends on runtime parameters */
/* fnv1_Result_size depends on runtime parameters */
/* fnv1_Condition_size depends on runtime parameters */
#if defined(google_protobuf_Struct_size)
#define APIEXTENSIONS_FN_PROTO_V1_RUN_FUNCTION_PB_H_MAX_SIZE fnv1_Schema_size
#define fnv1_Schema_size                         (6 + google_protobuf_Struct_size)
#endif

/* Mapping from canonical names (mangle_names or overridden package name) */
#define apiextensions_fn_proto_v1_Capability fnv1_Capability
#define apiextensions_fn_proto_v1_Ready fnv1_Ready
#define apiextensions_fn_proto_v1_Severity fnv1_Severity
#define apiextensions_fn_proto_v1_Target fnv1_Target
#define apiextensions_fn_proto_v1_Status fnv1_Status
#define apiextensions_fn_proto_v1_RunFunctionRequest fnv1_RunFunctionRequest
#define apiextensions_fn_proto_v1_RunFunctionRequest_ExtraResourcesEntry fnv1_RunFunctionRequest_ExtraResourcesEntry
#define apiextensions_fn_proto_v1_RunFunctionRequest_CredentialsEntry fnv1_RunFunctionRequest_CredentialsEntry
#define apiextensions_fn_proto_v1_RunFunctionRequest_RequiredResourcesEntry fnv1_RunFunctionRequest_RequiredResourcesEntry
#define apiextensions_fn_proto_v1_RunFunctionRequest_RequiredSchemasEntry fnv1_RunFunctionRequest_RequiredSchemasEntry
#define apiextensions_fn_proto_v1_Credentials fnv1_Credentials
#define apiextensions_fn_proto_v1_CredentialData fnv1_CredentialData
#define apiextensions_fn_proto_v1_CredentialData_DataEntry fnv1_CredentialData_DataEntry
#define apiextensions_fn_proto_v1_Resources fnv1_Resources
#define apiextensions_fn_proto_v1_RunFunctionResponse fnv1_RunFunctionResponse
#define apiextensions_fn_proto_v1_RequestMeta fnv1_RequestMeta
#define apiextensions_fn_proto_v1_Requirements fnv1_Requirements
#define apiextensions_fn_proto_v1_Requirements_ExtraResourcesEntry fnv1_Requirements_ExtraResourcesEntry
#define apiextensions_fn_proto_v1_Requirements_ResourcesEntry fnv1_Requirements_ResourcesEntry
#define apiextensions_fn_proto_v1_Requirements_SchemasEntry fnv1_Requirements_SchemasEntry
#define apiextensions_fn_proto_v1_SchemaSelector fnv1_SchemaSelector
#define apiextensions_fn_proto_v1_Schema fnv1_Schema
#define apiextensions_fn_proto_v1_ResourceSelector fnv1_ResourceSelector
#define apiextensions_fn_proto_v1_MatchLabels fnv1_MatchLabels
#define apiextensions_fn_proto_v1_MatchLabels_LabelsEntry fnv1_MatchLabels_LabelsEntry
#define apiextensions_fn_proto_v1_ResponseMeta fnv1_ResponseMeta
#define apiextensions_fn_proto_v1_State fnv1_State
#define apiextensions_fn_proto_v1_State_ResourcesEntry fnv1_State_ResourcesEntry
#define apiextensions_fn_proto_v1_Resource fnv1_Resource
#define apiextensions_fn_proto_v1_Resource_ConnectionDetailsEntry fnv1_Resource_ConnectionDetailsEntry
#define apiextensions_fn_proto_v1_Result fnv1_Result
#define apiextensions_fn_proto_v1_Condition fnv1_Condition
#define _apiextensions_fn_proto_v1_Capability_MIN _fnv1_Capability_MIN
#define _apiextensions_fn_proto_v1_Capability_MAX _fnv1_Capability_MAX
#define _apiextensions_fn_proto_v1_Capability_ARRAYSIZE _fnv1_Capability_ARRAYSIZE
#define _apiextensions_fn_proto_v1_Ready_MIN _fnv1_Ready_MIN
#define _apiextensions_fn_proto_v1_Ready_MAX _fnv1_Ready_MAX
#define _apiextensions_fn_proto_v1_Ready_ARRAYSIZE _fnv1_Ready_ARRAYSIZE
#define _apiextensions_fn_proto_v1_Severity_MIN _fnv1_Severity_MIN
#define _apiextensions_fn_proto_v1_Severity_MAX _fnv1_Severity_MAX
#define _apiextensions_fn_proto_v1_Severity_ARRAYSIZE _fnv1_Severity_ARRAYSIZE
#define _apiextensions_fn_proto_v1_Target_MIN _fnv1_Target_MIN
#define _apiextensions_fn_proto_v1_Target_MAX _fnv1_Target_MAX
#define _apiextensions_fn_proto_v1_Target_ARRAYSIZE _fnv1_Target_ARRAYSIZE
#define _apiextensions_fn_proto_v1_Status_MIN _fnv1_Status_MIN
#define _apiextensions_fn_proto_v1_Status_MAX _fnv1_Status_MAX
#define _apiextensions_fn_proto_v1_Status_ARRAYSIZE _fnv1_Status_ARRAYSIZE
#define apiextensions_fn_proto_v1_RunFunctionRequest_init_default fnv1_RunFunctionRequest_init_default
#define apiextensions_fn_proto_v1_RunFunctionRequest_ExtraResourcesEntry_init_default fnv1_RunFunctionRequest_ExtraResourcesEntry_init_default
#define apiextensions_fn_proto_v1_RunFunctionRequest_CredentialsEntry_init_default fnv1_RunFunctionRequest_CredentialsEntry_init_default
#define apiextensions_fn_proto_v1_RunFunctionRequest_RequiredResourcesEntry_init_default fnv1_RunFunctionRequest_RequiredResourcesEntry_init_default
#define apiextensions_fn_proto_v1_RunFunctionRequest_RequiredSchemasEntry_init_default fnv1_RunFunctionRequest_RequiredSchemasEntry_init_default
#define apiextensions_fn_proto_v1_Credentials_init_default fnv1_Credentials_init_default
#define apiextensions_fn_proto_v1_CredentialData_init_default fnv1_CredentialData_init_default
#define apiextensions_fn_proto_v1_CredentialData_DataEntry_init_default fnv1_CredentialData_DataEntry_init_default
#define apiextensions_fn_proto_v1_Resources_init_default fnv1_Resources_init_default
#define apiextensions_fn_proto_v1_RunFunctionResponse_init_default fnv1_RunFunctionResponse_init_default
#define apiextensions_fn_proto_v1_RequestMeta_init_default fnv1_RequestMeta_init_default
#define apiextensions_fn_proto_v1_Requirements_init_default fnv1_Requirements_init_default
#define apiextensions_fn_proto_v1_Requirements_ExtraResourcesEntry_init_default fnv1_Requirements_ExtraResourcesEntry_init_default
#define apiextensions_fn_proto_v1_Requirements_ResourcesEntry_init_default fnv1_Requirements_ResourcesEntry_init_default
#define apiextensions_fn_proto_v1_Requirements_SchemasEntry_init_default fnv1_Requirements_SchemasEntry_init_default
#define apiextensions_fn_proto_v1_SchemaSelector_init_default fnv1_SchemaSelector_init_default
#define apiextensions_fn_proto_v1_Schema_init_default fnv1_Schema_init_default
#define apiextensions_fn_proto_v1_ResourceSelector_init_default fnv1_ResourceSelector_init_default
#define apiextensions_fn_proto_v1_MatchLabels_init_default fnv1_MatchLabels_init_default
#define apiextensions_fn_proto_v1_MatchLabels_LabelsEntry_init_default fnv1_MatchLabels_LabelsEntry_init_default
#define apiextensions_fn_proto_v1_ResponseMeta_init_default fnv1_ResponseMeta_init_default
#define apiextensions_fn_proto_v1_State_init_default fnv1_State_init_default
#define apiextensions_fn_proto_v1_State_ResourcesEntry_init_default fnv1_State_ResourcesEntry_init_default
#define apiextensions_fn_proto_v1_Resource_init_default fnv1_Resource_init_default
#define apiextensions_fn_proto_v1_Resource_ConnectionDetailsEntry_init_default fnv1_Resource_ConnectionDetailsEntry_init_default
#define apiextensions_fn_proto_v1_Result_init_default fnv1_Result_init_default
#define apiextensions_fn_proto_v1_Condition_init_default fnv1_Condition_init_default
#define apiextensions_fn_proto_v1_RunFunctionRequest_init_zero fnv1_RunFunctionRequest_init_zero
#define apiextensions_fn_proto_v1_RunFunctionRequest_ExtraResourcesEntry_init_zero fnv1_RunFunctionRequest_ExtraResourcesEntry_init_zero
#define apiextensions_fn_proto_v1_RunFunctionRequest_CredentialsEntry_init_zero fnv1_RunFunctionRequest_CredentialsEntry_init_zero
#define apiextensions_fn_proto_v1_RunFunctionRequest_RequiredResourcesEntry_init_zero fnv1_RunFunctionRequest_RequiredResourcesEntry_init_zero
#define apiextensions_fn_proto_v1_RunFunctionRequest_RequiredSchemasEntry_init_zero fnv1_RunFunctionRequest_RequiredSchemasEntry_init_zero
#define apiextensions_fn_proto_v1_Credentials_init_zero fnv1_Credentials_init_zero
#define apiextensions_fn_proto_v1_CredentialData_init_zero fnv1_CredentialData_init_zero
#define apiextensions_fn_proto_v1_CredentialData_DataEntry_init_zero fnv1_CredentialData_DataEntry_init_zero
#define apiextensions_fn_proto_v1_Resources_init_zero fnv1_Resources_init_zero
#define apiextensions_fn_proto_v1_RunFunctionResponse_init_zero fnv1_RunFunctionResponse_init_zero
#define apiextensions_fn_proto_v1_RequestMeta_init_zero fnv1_RequestMeta_init_zero
#define apiextensions_fn_proto_v1_Requirements_init_zero fnv1_Requirements_init_zero
#define apiextensions_fn_proto_v1_Requirements_ExtraResourcesEntry_init_zero fnv1_Requirements_ExtraResourcesEntry_init_zero
#define apiextensions_fn_proto_v1_Requirements_ResourcesEntry_init_zero fnv1_Requirements_ResourcesEntry_init_zero
#define apiextensions_fn_proto_v1_Requirements_SchemasEntry_init_zero fnv1_Requirements_SchemasEntry_init_zero
#define apiextensions_fn_proto_v1_SchemaSelector_init_zero fnv1_SchemaSelector_init_zero
#define apiextensions_fn_proto_v1_Schema_init_zero fnv1_Schema_init_zero
#define apiextensions_fn_proto_v1_ResourceSelector_init_zero fnv1_ResourceSelector_init_zero
#define apiextensions_fn_proto_v1_MatchLabels_init_zero fnv1_MatchLabels_init_zero
#define apiextensions_fn_proto_v1_MatchLabels_LabelsEntry_init_zero fnv1_MatchLabels_LabelsEntry_init_zero
#define apiextensions_fn_proto_v1_ResponseMeta_init_zero fnv1_ResponseMeta_init_zero
#define apiextensions_fn_proto_v1_State_init_zero fnv1_State_init_zero
#define apiextensions_fn_proto_v1_State_ResourcesEntry_init_zero fnv1_State_ResourcesEntry_init_zero
#define apiextensions_fn_proto_v1_Resource_init_zero fnv1_Resource_init_zero
#define apiextensions_fn_proto_v1_Resource_ConnectionDetailsEntry_init_zero fnv1_Resource_ConnectionDetailsEntry_init_zero
#define apiextensions_fn_proto_v1_Result_init_zero fnv1_Result_init_zero
#define apiextensions_fn_proto_v1_Condition_init_zero fnv1_Condition_init_zero

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
