/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "run_function.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fnv1_RunFunctionRequest, fnv1_RunFunctionRequest, 2)


PB_BIND(fnv1_RunFunctionRequest_ExtraResourcesEntry, fnv1_RunFunctionRequest_ExtraResourcesEntry, AUTO)


PB_BIND(fnv1_RunFunctionRequest_CredentialsEntry, fnv1_RunFunctionRequest_CredentialsEntry, AUTO)


PB_BIND(fnv1_RunFunctionRequest_RequiredResourcesEntry, fnv1_RunFunctionRequest_RequiredResourcesEntry, AUTO)


PB_BIND(fnv1_RunFunctionRequest_RequiredSchemasEntry, fnv1_RunFunctionRequest_RequiredSchemasEntry, AUTO)


PB_BIND(fnv1_Credentials, fnv1_Credentials, AUTO)


PB_BIND(fnv1_CredentialData, fnv1_CredentialData, AUTO)


PB_BIND(fnv1_CredentialData_DataEntry, fnv1_CredentialData_DataEntry, AUTO)


PB_BIND(fnv1_Resources, fnv1_Resources, AUTO)


PB_BIND(fnv1_RunFunctionResponse, fnv1_RunFunctionResponse, AUTO)


PB_BIND(fnv1_RequestMeta, fnv1_RequestMeta, AUTO)


PB_BIND(fnv1_Requirements, fnv1_Requirements, AUTO)


PB_BIND(fnv1_Requirements_ExtraResourcesEntry, fnv1_Requirements_ExtraResourcesEntry, AUTO)


PB_BIND(fnv1_Requirements_ResourcesEntry, fnv1_Requirements_ResourcesEntry, AUTO)


PB_BIND(fnv1_Requirements_SchemasEntry, fnv1_Requirements_SchemasEntry, AUTO)


PB_BIND(fnv1_SchemaSelector, fnv1_SchemaSelector, AUTO)


PB_BIND(fnv1_Schema, fnv1_Schema, AUTO)


PB_BIND(fnv1_ResourceSelector, fnv1_ResourceSelector, AUTO)


PB_BIND(fnv1_MatchLabels, fnv1_MatchLabels, AUTO)


PB_BIND(fnv1_MatchLabels_LabelsEntry, fnv1_MatchLabels_LabelsEntry, AUTO)


PB_BIND(fnv1_ResponseMeta, fnv1_ResponseMeta, AUTO)


PB_BIND(fnv1_State, fnv1_State, AUTO)


PB_BIND(fnv1_State_ResourcesEntry, fnv1_State_ResourcesEntry, AUTO)


PB_BIND(fnv1_Resource, fnv1_Resource, AUTO)


PB_BIND(fnv1_Resource_ConnectionDetailsEntry, fnv1_Resource_ConnectionDetailsEntry, AUTO)


PB_BIND(fnv1_Result, fnv1_Result, AUTO)


PB_BIND(fnv1_Condition, fnv1_Condition, AUTO)













