// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

export enum Capability {
  CAPABILITY_UNSPECIFIED = 0,
  CAPABILITY_CAPABILITIES = 1,
  CAPABILITY_REQUIRED_RESOURCES = 2,
  CAPABILITY_CREDENTIALS = 3,
  CAPABILITY_CONDITIONS = 4,
  CAPABILITY_REQUIRED_SCHEMAS = 5,
}
