// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { CredentialData } from "./CredentialData";

export class Credentials {
  static encode(message: Credentials, writer: Writer): void {
    const credentialData = message.credentialData;
    if (credentialData !== null) {
      writer.uint32(10);
      writer.fork();
      CredentialData.encode(credentialData, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Credentials {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Credentials();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.credentialData = CredentialData.decode(
            reader,
            reader.uint32()
          );
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  credentialData: CredentialData | null;

  constructor(credentialData: CredentialData | null = null) {
    this.credentialData = credentialData;
  }
}
