// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";

export class CredentialData {
  static encode(message: CredentialData, writer: Writer): void {
    const data = message.data;
    if (data !== null) {
      const dataKeys = data.keys();
      for (let i: i32 = 0; i < dataKeys.length; ++i) {
        const dataKey = dataKeys[i];
        writer.uint32(10);
        writer.fork();
        writer.uint32(10);
        writer.string(dataKey);
        writer.uint32(18);
        writer.bytes(data.get(dataKey));
        writer.ldelim();
      }
    }
  }

  static decode(reader: Reader, length: i32): CredentialData {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CredentialData();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          let dataKey: string = "";
          let dataValue: Uint8Array = new Uint8Array(0);
          let dataHasKey: bool = false;
          let dataHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                dataKey = reader.string();
                dataHasKey = true;
                break;

              case 2:
                dataValue = reader.bytes();
                dataHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.data === null) {
              message.data = new Map<string, Uint8Array>();
            }
            const data = message.data;
            if (data !== null && dataHasKey && dataHasValue) {
              data.set(dataKey, dataValue);
            }
          }
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  data: Map<string, Uint8Array>;

  constructor(data: Map<string, Uint8Array> = new Map()) {
    this.data = data;
  }
}
