// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";

export class MatchLabels {
  static encode(message: MatchLabels, writer: Writer): void {
    const labels = message.labels;
    if (labels !== null) {
      const labelsKeys = labels.keys();
      for (let i: i32 = 0; i < labelsKeys.length; ++i) {
        const labelsKey = labelsKeys[i];
        writer.uint32(10);
        writer.fork();
        writer.uint32(10);
        writer.string(labelsKey);
        writer.uint32(18);
        writer.string(labels.get(labelsKey));
        writer.ldelim();
      }
    }
  }

  static decode(reader: Reader, length: i32): MatchLabels {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MatchLabels();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          let labelsKey: string = "";
          let labelsValue: string = "";
          let labelsHasKey: bool = false;
          let labelsHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                labelsKey = reader.string();
                labelsHasKey = true;
                break;

              case 2:
                labelsValue = reader.string();
                labelsHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.labels === null) {
              message.labels = new Map<string, string>();
            }
            const labels = message.labels;
            if (labels !== null && labelsHasKey && labelsHasValue) {
              labels.set(labelsKey, labelsValue);
            }
          }
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  labels: Map<string, string>;

  constructor(labels: Map<string, string> = new Map()) {
    this.labels = labels;
  }
}
