// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

export enum Ready {
  READY_UNSPECIFIED = 0,
  READY_TRUE = 1,
  READY_FALSE = 2,
}
