// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { ResourceSelector } from "./ResourceSelector";
import { SchemaSelector } from "./SchemaSelector";

export class Requirements {
  static encode(message: Requirements, writer: Writer): void {
    const extraResources = message.extraResources;
    if (extraResources !== null) {
      const extraResourcesKeys = extraResources.keys();
      for (let i: i32 = 0; i < extraResourcesKeys.length; ++i) {
        const extraResourcesKey = extraResourcesKeys[i];
        writer.uint32(10);
        writer.fork();
        writer.uint32(10);
        writer.string(extraResourcesKey);
        writer.uint32(18);
        writer.fork();
        ResourceSelector.encode(extraResources.get(extraResourcesKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }

    const resources = message.resources;
    if (resources !== null) {
      const resourcesKeys = resources.keys();
      for (let i: i32 = 0; i < resourcesKeys.length; ++i) {
        const resourcesKey = resourcesKeys[i];
        writer.uint32(18);
        writer.fork();
        writer.uint32(10);
        writer.string(resourcesKey);
        writer.uint32(18);
        writer.fork();
        ResourceSelector.encode(resources.get(resourcesKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }

    const schemas = message.schemas;
    if (schemas !== null) {
      const schemasKeys = schemas.keys();
      for (let i: i32 = 0; i < schemasKeys.length; ++i) {
        const schemasKey = schemasKeys[i];
        writer.uint32(26);
        writer.fork();
        writer.uint32(10);
        writer.string(schemasKey);
        writer.uint32(18);
        writer.fork();
        SchemaSelector.encode(schemas.get(schemasKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }
  }

  static decode(reader: Reader, length: i32): Requirements {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Requirements();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          let extraResourcesKey: string = "";
          let extraResourcesValue: ResourceSelector | null = null;
          let extraResourcesHasKey: bool = false;
          let extraResourcesHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                extraResourcesKey = reader.string();
                extraResourcesHasKey = true;
                break;

              case 2:
                extraResourcesValue = ResourceSelector.decode(
                  reader,
                  reader.uint32()
                );
                extraResourcesHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.extraResources === null) {
              message.extraResources = new Map<string, ResourceSelector>();
            }
            const extraResources = message.extraResources;
            if (
              extraResources !== null &&
              extraResourcesHasKey &&
              extraResourcesHasValue &&
              extraResourcesValue !== null
            ) {
              extraResources.set(extraResourcesKey, extraResourcesValue);
            }
          }
          break;

        case 2:
          let resourcesKey: string = "";
          let resourcesValue: ResourceSelector | null = null;
          let resourcesHasKey: bool = false;
          let resourcesHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                resourcesKey = reader.string();
                resourcesHasKey = true;
                break;

              case 2:
                resourcesValue = ResourceSelector.decode(
                  reader,
                  reader.uint32()
                );
                resourcesHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.resources === null) {
              message.resources = new Map<string, ResourceSelector>();
            }
            const resources = message.resources;
            if (
              resources !== null &&
              resourcesHasKey &&
              resourcesHasValue &&
              resourcesValue !== null
            ) {
              resources.set(resourcesKey, resourcesValue);
            }
          }
          break;

        case 3:
          let schemasKey: string = "";
          let schemasValue: SchemaSelector | null = null;
          let schemasHasKey: bool = false;
          let schemasHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                schemasKey = reader.string();
                schemasHasKey = true;
                break;

              case 2:
                schemasValue = SchemaSelector.decode(reader, reader.uint32());
                schemasHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.schemas === null) {
              message.schemas = new Map<string, SchemaSelector>();
            }
            const schemas = message.schemas;
            if (
              schemas !== null &&
              schemasHasKey &&
              schemasHasValue &&
              schemasValue !== null
            ) {
              schemas.set(schemasKey, schemasValue);
            }
          }
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  extraResources: Map<string, ResourceSelector>;
  resources: Map<string, ResourceSelector>;
  schemas: Map<string, SchemaSelector>;

  constructor(
    extraResources: Map<string, ResourceSelector> = new Map(),
    resources: Map<string, ResourceSelector> = new Map(),
    schemas: Map<string, SchemaSelector> = new Map()
  ) {
    this.extraResources = extraResources;
    this.resources = resources;
    this.schemas = schemas;
  }
}
