// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { Resource } from "./Resource";

export class Resources {
  static encode(message: Resources, writer: Writer): void {
    const items = message.items;
    for (let i: i32 = 0; i < items.length; ++i) {
      writer.uint32(10);
      writer.fork();
      Resource.encode(items[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Resources {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Resources();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.items.push(Resource.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  items: Array<Resource>;

  constructor(items: Array<Resource> = []) {
    this.items = items;
  }
}
