// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { MatchLabels } from "./MatchLabels";

export class ResourceSelector {
  static encode(message: ResourceSelector, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.apiVersion);

    writer.uint32(18);
    writer.string(message.kind);

    writer.uint32(26);
    writer.string(message.matchName);

    const matchLabels = message.matchLabels;
    if (matchLabels !== null) {
      writer.uint32(34);
      writer.fork();
      MatchLabels.encode(matchLabels, writer);
      writer.ldelim();
    }

    writer.uint32(42);
    writer.string(message.namespace);
  }

  static decode(reader: Reader, length: i32): ResourceSelector {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ResourceSelector();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.apiVersion = reader.string();
          break;

        case 2:
          message.kind = reader.string();
          break;

        case 3:
          message.matchName = reader.string();
          break;

        case 4:
          message.matchLabels = MatchLabels.decode(reader, reader.uint32());
          break;

        case 5:
          message.namespace = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  apiVersion: string;
  kind: string;
  matchName: string;
  matchLabels: MatchLabels | null;
  namespace: string;

  constructor(
    apiVersion: string = "",
    kind: string = "",
    matchName: string = "",
    matchLabels: MatchLabels | null = null,
    namespace: string = ""
  ) {
    this.apiVersion = apiVersion;
    this.kind = kind;
    this.matchName = matchName;
    this.matchLabels = matchLabels;
    this.namespace = namespace;
  }
}
