// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { Struct } from "../../../../google/protobuf/Struct";
import { Ready } from "./Ready";

export class Resource {
  static encode(message: Resource, writer: Writer): void {
    const resource = message.resource;
    if (resource !== null) {
      writer.uint32(10);
      writer.fork();
      Struct.encode(resource, writer);
      writer.ldelim();
    }

    const connectionDetails = message.connectionDetails;
    if (connectionDetails !== null) {
      const connectionDetailsKeys = connectionDetails.keys();
      for (let i: i32 = 0; i < connectionDetailsKeys.length; ++i) {
        const connectionDetailsKey = connectionDetailsKeys[i];
        writer.uint32(18);
        writer.fork();
        writer.uint32(10);
        writer.string(connectionDetailsKey);
        writer.uint32(18);
        writer.bytes(connectionDetails.get(connectionDetailsKey));
        writer.ldelim();
      }
    }

    writer.uint32(24);
    writer.int32(message.ready);
  }

  static decode(reader: Reader, length: i32): Resource {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Resource();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.resource = Struct.decode(reader, reader.uint32());
          break;

        case 2:
          let connectionDetailsKey: string = "";
          let connectionDetailsValue: Uint8Array = new Uint8Array(0);
          let connectionDetailsHasKey: bool = false;
          let connectionDetailsHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                connectionDetailsKey = reader.string();
                connectionDetailsHasKey = true;
                break;

              case 2:
                connectionDetailsValue = reader.bytes();
                connectionDetailsHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.connectionDetails === null) {
              message.connectionDetails = new Map<string, Uint8Array>();
            }
            const connectionDetails = message.connectionDetails;
            if (
              connectionDetails !== null &&
              connectionDetailsHasKey &&
              connectionDetailsHasValue
            ) {
              connectionDetails.set(
                connectionDetailsKey,
                connectionDetailsValue
              );
            }
          }
          break;

        case 3:
          message.ready = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  resource: Struct | null;
  connectionDetails: Map<string, Uint8Array>;
  ready: Ready;

  constructor(
    resource: Struct | null = null,
    connectionDetails: Map<string, Uint8Array> = new Map(),
    ready: Ready = 0
  ) {
    this.resource = resource;
    this.connectionDetails = connectionDetails;
    this.ready = ready;
  }
}
