// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { Duration } from "../../../../google/protobuf/Duration";

export class ResponseMeta {
  static encode(message: ResponseMeta, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.tag);

    const ttl = message.ttl;
    if (ttl !== null) {
      writer.uint32(18);
      writer.fork();
      Duration.encode(ttl, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ResponseMeta {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ResponseMeta();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.tag = reader.string();
          break;

        case 2:
          message.ttl = Duration.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  tag: string;
  ttl: Duration | null;

  constructor(tag: string = "", ttl: Duration | null = null) {
    this.tag = tag;
    this.ttl = ttl;
  }
}
