// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { ResponseMeta } from "./ResponseMeta";
import { State } from "./State";
import { Result } from "./Result";
import { Struct } from "../../../../google/protobuf/Struct";
import { Requirements } from "./Requirements";
import { Condition } from "./Condition";

export class RunFunctionResponse {
  static encode(message: RunFunctionResponse, writer: Writer): void {
    const meta = message.meta;
    if (meta !== null) {
      writer.uint32(10);
      writer.fork();
      ResponseMeta.encode(meta, writer);
      writer.ldelim();
    }

    const desired = message.desired;
    if (desired !== null) {
      writer.uint32(18);
      writer.fork();
      State.encode(desired, writer);
      writer.ldelim();
    }

    const results = message.results;
    for (let i: i32 = 0; i < results.length; ++i) {
      writer.uint32(26);
      writer.fork();
      Result.encode(results[i], writer);
      writer.ldelim();
    }

    const context = message.context;
    if (context !== null) {
      writer.uint32(34);
      writer.fork();
      Struct.encode(context, writer);
      writer.ldelim();
    }

    const requirements = message.requirements;
    if (requirements !== null) {
      writer.uint32(42);
      writer.fork();
      Requirements.encode(requirements, writer);
      writer.ldelim();
    }

    const conditions = message.conditions;
    for (let i: i32 = 0; i < conditions.length; ++i) {
      writer.uint32(50);
      writer.fork();
      Condition.encode(conditions[i], writer);
      writer.ldelim();
    }

    const output = message.output;
    if (output !== null) {
      writer.uint32(58);
      writer.fork();
      Struct.encode(output, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): RunFunctionResponse {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RunFunctionResponse();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.meta = ResponseMeta.decode(reader, reader.uint32());
          break;

        case 2:
          message.desired = State.decode(reader, reader.uint32());
          break;

        case 3:
          message.results.push(Result.decode(reader, reader.uint32()));
          break;

        case 4:
          message.context = Struct.decode(reader, reader.uint32());
          break;

        case 5:
          message.requirements = Requirements.decode(reader, reader.uint32());
          break;

        case 6:
          message.conditions.push(Condition.decode(reader, reader.uint32()));
          break;

        case 7:
          message.output = Struct.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  meta: ResponseMeta | null;
  desired: State | null;
  results: Array<Result>;
  context: Struct | null;
  requirements: Requirements | null;
  conditions: Array<Condition>;
  output: Struct | null;

  constructor(
    meta: ResponseMeta | null = null,
    desired: State | null = null,
    results: Array<Result> = [],
    context: Struct | null = null,
    requirements: Requirements | null = null,
    conditions: Array<Condition> = [],
    output: Struct | null = null
  ) {
    this.meta = meta;
    this.desired = desired;
    this.results = results;
    this.context = context;
    this.requirements = requirements;
    this.conditions = conditions;
    this.output = output;
  }
}
