// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { RequestMeta } from "./RequestMeta";
import { State } from "./State";
import { Struct } from "../../../../google/protobuf/Struct";
import { Resources } from "./Resources";
import { Credentials } from "./Credentials";
import { Schema } from "./Schema";

export class RunFunctionRequest {
  static encode(message: RunFunctionRequest, writer: Writer): void {
    const meta = message.meta;
    if (meta !== null) {
      writer.uint32(10);
      writer.fork();
      RequestMeta.encode(meta, writer);
      writer.ldelim();
    }

    const observed = message.observed;
    if (observed !== null) {
      writer.uint32(18);
      writer.fork();
      State.encode(observed, writer);
      writer.ldelim();
    }

    const desired = message.desired;
    if (desired !== null) {
      writer.uint32(26);
      writer.fork();
      State.encode(desired, writer);
      writer.ldelim();
    }

    const input = message.input;
    if (input !== null) {
      writer.uint32(34);
      writer.fork();
      Struct.encode(input, writer);
      writer.ldelim();
    }

    const context = message.context;
    if (context !== null) {
      writer.uint32(42);
      writer.fork();
      Struct.encode(context, writer);
      writer.ldelim();
    }

    const extraResources = message.extraResources;
    if (extraResources !== null) {
      const extraResourcesKeys = extraResources.keys();
      for (let i: i32 = 0; i < extraResourcesKeys.length; ++i) {
        const extraResourcesKey = extraResourcesKeys[i];
        writer.uint32(50);
        writer.fork();
        writer.uint32(10);
        writer.string(extraResourcesKey);
        writer.uint32(18);
        writer.fork();
        Resources.encode(extraResources.get(extraResourcesKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }

    const credentials = message.credentials;
    if (credentials !== null) {
      const credentialsKeys = credentials.keys();
      for (let i: i32 = 0; i < credentialsKeys.length; ++i) {
        const credentialsKey = credentialsKeys[i];
        writer.uint32(58);
        writer.fork();
        writer.uint32(10);
        writer.string(credentialsKey);
        writer.uint32(18);
        writer.fork();
        Credentials.encode(credentials.get(credentialsKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }

    const requiredResources = message.requiredResources;
    if (requiredResources !== null) {
      const requiredResourcesKeys = requiredResources.keys();
      for (let i: i32 = 0; i < requiredResourcesKeys.length; ++i) {
        const requiredResourcesKey = requiredResourcesKeys[i];
        writer.uint32(66);
        writer.fork();
        writer.uint32(10);
        writer.string(requiredResourcesKey);
        writer.uint32(18);
        writer.fork();
        Resources.encode(requiredResources.get(requiredResourcesKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }

    const requiredSchemas = message.requiredSchemas;
    if (requiredSchemas !== null) {
      const requiredSchemasKeys = requiredSchemas.keys();
      for (let i: i32 = 0; i < requiredSchemasKeys.length; ++i) {
        const requiredSchemasKey = requiredSchemasKeys[i];
        writer.uint32(74);
        writer.fork();
        writer.uint32(10);
        writer.string(requiredSchemasKey);
        writer.uint32(18);
        writer.fork();
        Schema.encode(requiredSchemas.get(requiredSchemasKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }
  }

  static decode(reader: Reader, length: i32): RunFunctionRequest {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new RunFunctionRequest();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.meta = RequestMeta.decode(reader, reader.uint32());
          break;

        case 2:
          message.observed = State.decode(reader, reader.uint32());
          break;

        case 3:
          message.desired = State.decode(reader, reader.uint32());
          break;

        case 4:
          message.input = Struct.decode(reader, reader.uint32());
          break;

        case 5:
          message.context = Struct.decode(reader, reader.uint32());
          break;

        case 6:
          let extraResourcesKey: string = "";
          let extraResourcesValue: Resources | null = null;
          let extraResourcesHasKey: bool = false;
          let extraResourcesHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                extraResourcesKey = reader.string();
                extraResourcesHasKey = true;
                break;

              case 2:
                extraResourcesValue = Resources.decode(reader, reader.uint32());
                extraResourcesHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.extraResources === null) {
              message.extraResources = new Map<string, Resources>();
            }
            const extraResources = message.extraResources;
            if (
              extraResources !== null &&
              extraResourcesHasKey &&
              extraResourcesHasValue &&
              extraResourcesValue !== null
            ) {
              extraResources.set(extraResourcesKey, extraResourcesValue);
            }
          }
          break;

        case 7:
          let credentialsKey: string = "";
          let credentialsValue: Credentials | null = null;
          let credentialsHasKey: bool = false;
          let credentialsHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                credentialsKey = reader.string();
                credentialsHasKey = true;
                break;

              case 2:
                credentialsValue = Credentials.decode(reader, reader.uint32());
                credentialsHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.credentials === null) {
              message.credentials = new Map<string, Credentials>();
            }
            const credentials = message.credentials;
            if (
              credentials !== null &&
              credentialsHasKey &&
              credentialsHasValue &&
              credentialsValue !== null
            ) {
              credentials.set(credentialsKey, credentialsValue);
            }
          }
          break;

        case 8:
          let requiredResourcesKey: string = "";
          let requiredResourcesValue: Resources | null = null;
          let requiredResourcesHasKey: bool = false;
          let requiredResourcesHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                requiredResourcesKey = reader.string();
                requiredResourcesHasKey = true;
                break;

              case 2:
                requiredResourcesValue = Resources.decode(
                  reader,
                  reader.uint32()
                );
                requiredResourcesHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.requiredResources === null) {
              message.requiredResources = new Map<string, Resources>();
            }
            const requiredResources = message.requiredResources;
            if (
              requiredResources !== null &&
              requiredResourcesHasKey &&
              requiredResourcesHasValue &&
              requiredResourcesValue !== null
            ) {
              requiredResources.set(
                requiredResourcesKey,
                requiredResourcesValue
              );
            }
          }
          break;

        case 9:
          let requiredSchemasKey: string = "";
          let requiredSchemasValue: Schema | null = null;
          let requiredSchemasHasKey: bool = false;
          let requiredSchemasHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                requiredSchemasKey = reader.string();
                requiredSchemasHasKey = true;
                break;

              case 2:
                requiredSchemasValue = Schema.decode(reader, reader.uint32());
                requiredSchemasHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.requiredSchemas === null) {
              message.requiredSchemas = new Map<string, Schema>();
            }
            const requiredSchemas = message.requiredSchemas;
            if (
              requiredSchemas !== null &&
              requiredSchemasHasKey &&
              requiredSchemasHasValue &&
              requiredSchemasValue !== null
            ) {
              requiredSchemas.set(requiredSchemasKey, requiredSchemasValue);
            }
          }
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  meta: RequestMeta | null;
  observed: State | null;
  desired: State | null;
  input: Struct | null;
  context: Struct | null;
  extraResources: Map<string, Resources>;
  credentials: Map<string, Credentials>;
  requiredResources: Map<string, Resources>;
  requiredSchemas: Map<string, Schema>;

  constructor(
    meta: RequestMeta | null = null,
    observed: State | null = null,
    desired: State | null = null,
    input: Struct | null = null,
    context: Struct | null = null,
    extraResources: Map<string, Resources> = new Map(),
    credentials: Map<string, Credentials> = new Map(),
    requiredResources: Map<string, Resources> = new Map(),
    requiredSchemas: Map<string, Schema> = new Map()
  ) {
    this.meta = meta;
    this.observed = observed;
    this.desired = desired;
    this.input = input;
    this.context = context;
    this.extraResources = extraResources;
    this.credentials = credentials;
    this.requiredResources = requiredResources;
    this.requiredSchemas = requiredSchemas;
  }
}
