// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { Struct } from "../../../../google/protobuf/Struct";

export class Schema {
  static encode(message: Schema, writer: Writer): void {
    const openapiV3 = message.openapiV3;
    if (openapiV3 !== null) {
      writer.uint32(10);
      writer.fork();
      Struct.encode(openapiV3, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Schema {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Schema();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.openapiV3 = Struct.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  openapiV3: Struct | null;

  constructor(openapiV3: Struct | null = null) {
    this.openapiV3 = openapiV3;
  }
}
