// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

export enum Severity {
  SEVERITY_UNSPECIFIED = 0,
  SEVERITY_FATAL = 1,
  SEVERITY_WARNING = 2,
  SEVERITY_NORMAL = 3,
}
