// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

import { Writer, Reader } from "as-proto/assembly";
import { Resource } from "./Resource";

export class State {
  static encode(message: State, writer: Writer): void {
    const composite = message.composite;
    if (composite !== null) {
      writer.uint32(10);
      writer.fork();
      Resource.encode(composite, writer);
      writer.ldelim();
    }

    const resources = message.resources;
    if (resources !== null) {
      const resourcesKeys = resources.keys();
      for (let i: i32 = 0; i < resourcesKeys.length; ++i) {
        const resourcesKey = resourcesKeys[i];
        writer.uint32(18);
        writer.fork();
        writer.uint32(10);
        writer.string(resourcesKey);
        writer.uint32(18);
        writer.fork();
        Resource.encode(resources.get(resourcesKey), writer);
        writer.ldelim();
        writer.ldelim();
      }
    }
  }

  static decode(reader: Reader, length: i32): State {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new State();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.composite = Resource.decode(reader, reader.uint32());
          break;

        case 2:
          let resourcesKey: string = "";
          let resourcesValue: Resource | null = null;
          let resourcesHasKey: bool = false;
          let resourcesHasValue: bool = false;
          for (
            const end: usize = reader.ptr + reader.uint32();
            reader.ptr < end;

          ) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
              case 1:
                resourcesKey = reader.string();
                resourcesHasKey = true;
                break;

              case 2:
                resourcesValue = Resource.decode(reader, reader.uint32());
                resourcesHasValue = true;
                break;

              default:
                reader.skipType(tag & 7);
                break;
            }
            if (message.resources === null) {
              message.resources = new Map<string, Resource>();
            }
            const resources = message.resources;
            if (
              resources !== null &&
              resourcesHasKey &&
              resourcesHasValue &&
              resourcesValue !== null
            ) {
              resources.set(resourcesKey, resourcesValue);
            }
          }
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  composite: Resource | null;
  resources: Map<string, Resource>;

  constructor(
    composite: Resource | null = null,
    resources: Map<string, Resource> = new Map()
  ) {
    this.composite = composite;
    this.resources = resources;
  }
}
