// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

export enum Status {
  STATUS_CONDITION_UNSPECIFIED = 0,
  STATUS_CONDITION_UNKNOWN = 1,
  STATUS_CONDITION_TRUE = 2,
  STATUS_CONDITION_FALSE = 3,
}
