// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v7.35.1

export enum Target {
  TARGET_UNSPECIFIED = 0,
  TARGET_COMPOSITE = 1,
  TARGET_COMPOSITE_AND_CLAIM = 2,
}
