// Code generated by protoc-gen-zig
///! package google.protobuf
const std = @import("std");

const protobuf = @import("protobuf");
const fd = protobuf.fd;

pub const Duration = protobuf.wkt.Duration;

pub const NullValue = protobuf.wkt.NullValue;

pub const Struct = protobuf.wkt.Struct;

pub const Value = protobuf.wkt.Value;

pub const ListValue = protobuf.wkt.ListValue;
