// Generated by `wit-bindgen` 0.62.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     wasi:io@0.2.12
//     wasi:clocks@0.2.12
//     wasi:random@0.2.12
//     wasi:filesystem@0.2.12
//     wasi:sockets@0.2.12
//     wasi:cli@0.2.12
//     wasi:http@0.2.12
//     local:guest

package wit_world

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

const (
	LogLevelDebug uint8 = 0
	LogLevelInfo  uint8 = 1
	LogLevelWarn  uint8 = 2
	LogLevelError uint8 = 3
)

type LogLevel = uint8

//go:wasmimport $root log
func wasm_import_log(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr, arg4 uint32)

func Log(level LogLevel, msg string, kv []witTypes.Tuple2[string, string]) {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(msg))
	pinner.Pin(utf8)
	slice := kv
	length := uint32(len(slice))
	result := witRuntime.Allocate(pinner, uintptr(length*(4*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result, index*(4*4))
		utf80 := unsafe.Pointer(unsafe.StringData((element).F0))
		pinner.Pin(utf80)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).F0)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf80)))
		utf81 := unsafe.Pointer(unsafe.StringData((element).F1))
		pinner.Pin(utf81)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = uint32(uint32(len((element).F1)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uintptr(uintptr(utf81)))

	}

	wasm_import_log(int32(level), uintptr(utf8), uint32(len(msg)), uintptr(result), length)

}
