package wasmfn

import (
	"context"
	"fmt"
	"io"
	"os"
	"runtime/debug"
	"time"

	fnv1 "github.com/crossplane/function-sdk-go/proto/v1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/durationpb"
)

// defaultTTL matches function-sdk-go's response.DefaultTTL: how long
// Crossplane may reuse a response the guest did not stamp itself.
const defaultTTL = 60 * time.Second

// A Runner runs a composition function. *Function types generated by
// function-template-go satisfy it; embedding
// fnv1.UnimplementedFunctionRunnerServiceServer is not required.
type Runner interface {
	RunFunction(ctx context.Context, req *fnv1.RunFunctionRequest) (*fnv1.RunFunctionResponse, error)
}

var runner Runner

// stderr receives panic stacks; the host inherits the guest's stderr.
var stderr io.Writer = os.Stderr

// Register sets the Runner the wasmfn_run export dispatches to. Call it from
// an init function: the wasip1 c-shared build never executes main.
func Register(r Runner) {
	runner = r
}

// handle is the guest half of ABI v1: it decodes a RunFunctionRequest, runs
// the registered Runner and encodes the RunFunctionResponse. Every failure —
// including a returned error, a panic and an unusable request — becomes a
// fatal result so the host can always decode what comes back.
func handle(ctx context.Context, in []byte) []byte {
	req := &fnv1.RunFunctionRequest{}
	if err := proto.Unmarshal(in, req); err != nil {
		return encode(fatal(nil, fmt.Errorf("cannot decode RunFunctionRequest: %w", err)))
	}
	if runner == nil {
		return encode(fatal(req, fmt.Errorf("no Runner registered: call wasmfn.Register from an init function")))
	}
	return encode(run(ctx, req))
}

func run(ctx context.Context, req *fnv1.RunFunctionRequest) (rsp *fnv1.RunFunctionResponse) {
	defer func() {
		if r := recover(); r != nil {
			// The stack goes to stderr, which the host inherits, so it lands
			// next to the host's own logs instead of inside a Kubernetes
			// condition message.
			_, _ = fmt.Fprintf(stderr, "wasmfn: RunFunction panicked: %v\n%s", r, debug.Stack())
			rsp = fatal(req, fmt.Errorf("RunFunction panicked: %v", r))
		}
	}()
	rsp, err := runner.RunFunction(ctx, req)
	if err != nil {
		return fatal(req, err)
	}
	if rsp == nil {
		return to(req)
	}
	return rsp
}

// to is response.To without importing function-sdk-go/response, which would
// pull crossplane-runtime and Kubernetes apimachinery into every guest.
func to(req *fnv1.RunFunctionRequest) *fnv1.RunFunctionResponse {
	return &fnv1.RunFunctionResponse{
		Meta: &fnv1.ResponseMeta{Tag: req.GetMeta().GetTag(), Ttl: durationpb.New(defaultTTL)},
	}
}

// fatal is response.Fatal on a fresh response: a fatal result targeting the
// composite resource.
func fatal(req *fnv1.RunFunctionRequest, err error) *fnv1.RunFunctionResponse {
	rsp := &fnv1.RunFunctionResponse{}
	if req != nil {
		rsp = to(req)
	}
	rsp.Results = append(rsp.Results, &fnv1.Result{
		Severity: fnv1.Severity_SEVERITY_FATAL,
		Message:  err.Error(),
		Target:   fnv1.Target_TARGET_COMPOSITE.Enum(),
	})
	return rsp
}

func encode(rsp *fnv1.RunFunctionResponse) []byte {
	out, err := proto.Marshal(rsp)
	if err != nil {
		out, _ = proto.Marshal(fatal(nil, fmt.Errorf("cannot encode RunFunctionResponse: %w", err)))
	}
	return out
}
